 #config/routes/easy_admin.yaml
#easy_admin_bundle:
 # resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
  #prefix: /admin
  #type: annotation

#entities:
       # List the entity class name you want to manage
        #- App\Entity\Product
 #       - App\Entity\Program
